phone_home_proxy_host:  remote.stratuscom.com
phone_home_proxy_user:  digipi
phone_home_proxy_port:  14439
ansible_user: 'pi'

aprs_objects:
  - id: repeater
    name: "444.825ON"
    latitude: "{{ latitude }}"
    longitude: "{{ longitude }}"
    symbol: "/r"
    comment: "T131 NET WED1930 MTG1STTH"
  - id: hamfest
    name: "HFEST-09a"
    latitude: "4330.55N"
    longitude: "07952.62W"
    symbol: "\\h"
    comment: "146.52MHz BARC Ontario Hamfest. Sat Jul 9 9:00AM"
