# This role manages the configuration of aprx.
# We assume that aprx is already installed and the configuration goes into
# /etc/aprx.conf

- name: Make sure we have the local systemd directory
  file: path={{ systemd_unit_dir}} state=directory

- name: Setup systemd service unit for aprx
  template: src=aprx.service.jj2 dest={{ systemd_unit_dir }}/aprx.service

- name: Create APRX log directory
  file:
    path: /var/log/aprx
    state: directory
    mode: 0755

- name: Create the aprx config file
  template: src=aprx.conf dest=/etc/aprx.conf

- name: Restart aprx
  systemd: daemon_reload=yes name=aprx enabled=yes state=restarted
