
---
# This role sets up the sshd configuration on the gateway to allow
# port forwarding and let the remote systems be accessible through the
# gateway

- name: Allow port forwarding
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^GatewayPorts'
    line: 'GatewayPorts yes'

- name: Send Keepalive packets, so we notice dead partners
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^TCPKeepAlive'
    line: 'TCPKeepAlive yes'

- name: Set client keepalive interval
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^ClientAliveInterval'
    line: 'ClientAliveInterval 30'

- name: Allow tcp forwarding
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^AllowTcpForwarding'
    line: 'AllowTcpForwarding yes'
