---
# If aprx has any package dependencies, put them here...
# - name: Install development libraries for Gaucamoled
#   yum:  name={{ item }} state=present
#   with_items:
#     - cairo-devel
#     - libjpeg-turbo-devel
#     - libpng-devel
#     - uuid-devel
#     - freerdp-devel
#     - pango-devel
#     - libssh2-devel
#     - libvncserver-devel
#     - openssl-devel
#     - libvorbis-devel
#     - libtool
#     - "@Desktop"
#     - "@Desktop Platform"
#     - "@X Window System"
#     - "@Fonts"

# Use the 'pi' user for compiles - it's already there
- name: add group "{{ aprx_group }}"
  group: name={{ aprx_group }}
  become: True
  become_user:  root

- name: add user "{{ aprx_user }}"
  user: name={{ aprx_user }} group={{ aprx_group }} home=/home/{{ aprx_user }} createhome=yes
  become: True
  become_user:  root

- name: Download APRX sources
  get_url:
    url: http://thelifeofkenneth.com/aprx/release/aprx-2.9.0.tar.gz
    dest: /home/{{ aprx_user}}/aprx-2.9.0.tar.gz

# - name: Extract archive
#   command: chdir=/home/pi /bin/tar xvf /opt/APRX-server-0.9.9.tar.gz -C /opt/creates=/opt/APRX-server-0.9.9

- name: Extract archive
  unarchive:
    src: /home/{{ aprx_user}}/aprx-2.9.0.tar.gz
    dest: /home/{{ aprx_user }}
    owner: "{{ aprx_user }}"
    group: "{{ aprx_group }}"
    remote_src: True

- name: Run the configure tool
  shell: ./configure
  args:
    chdir: "/home/{{ aprx_user }}/aprx-2.9.0"
  become_user: "{{ aprx_user }}"
  become: true

- name: Make APRX
  shell: make
  args:
    chdir: "/home/{{ aprx_user}}/aprx-2.9.0"
  become_user: "{{ aprx_user }}"
  become: true

- name: Install APRX
  shell: make install
  args:
    chdir: "/home/{{ aprx_user}}/aprx-2.9.0"
