---
# If aprx has any package dependencies, put them here...
# - name: Install development libraries for Gaucamoled
#   yum:  name={{ item }} state=present
#   with_items:
#     - cairo-devel
#     - libjpeg-turbo-devel
#     - libpng-devel
#     - uuid-devel
#     - freerdp-devel
#     - pango-devel
#     - libssh2-devel
#     - libvncserver-devel
#     - openssl-devel
#     - libvorbis-devel
#     - libtool
#     - "@Desktop"
#     - "@Desktop Platform"
#     - "@X Window System"
#     - "@Fonts"

# Use the 'pi' user for compiles - it's already there
# - name: add group "pi"
#   group: name=pi
#
# - name: add user "pi"
#   user: name=pi group=pi home=/home/pi createhome=no
#   sudo: True

- name: Download APRX sources
  get_url: url=http://thelifeofkenneth.com/aprx/release/aprx-2.9.0.tar.gz dest=/home/pi/aprx-2.9.0.tar.gz

# - name: Extract archive
#   command: chdir=/home/pi /bin/tar xvf /opt/APRX-server-0.9.9.tar.gz -C /opt/creates=/opt/APRX-server-0.9.9

- name: Extract archive
  unarchive:
    src: http://thelifeofkenneth.com/aprx/release/aprx-2.9.0.tar.gz dest=/home/pi/aprx-2.9.0.tar.gz
    dest: /home/pi
    owner: pi
    group: pi
    remote_src: True

- name: Run the configure tool
  shell: chdir=/home/pi/aprx-2.9.0 ./configure
  become_user: pi
  become: true

- name: Make APRX
  shell: chdir=/home/pi/aprx-2.9.0 make
  become_user: pi
  become: true

- name: Install APRX
  shell: chdir=/home/pi/aprx-2.9.0 make install
