
---
# This playbook downloads, compiles and installs Direwolf and APRX

- hosts: direwolf_hosts
  roles:
    - direwolf

- hosts: share_tnc_hosts
    - rpi-nodejs
    - share_tnc

- hosts: aprx_hosts
  roles:
    - aprx
    - aprx_config
