
---
# This playbook downloads, compiles and installs Direwolf and APRX

- hosts: direwolf_hosts
  roles:
    - direwolf

- hosts: aprx_hosts
  roles:
    - rpi-nodejs
    - aprx
    - share_tnc
    - aprx_config
