
---
# This playbook configures infrastructure for the Burlington Amateur Radio Club
# In this script, we setup the remote access or 'phone_home' capability.
# So.. this playbook needs to be executed when you have local access.

# Alternately, if you have remote access through one of the gateways and you
# want to setup remote access through the other gateways, you can comment out
# the 'phone_home' line that corresponds to the gateway that you're currently
# using.

- hosts: remote_access
  name: 'Setup phone_home service'
  roles:
#    - phone_home
    - phone_home_2
    - phone_home_gw

- include: setup-ssh-users.yml
