
---

- hosts: remote_access
  tasks:
    # Copy the authorized_keys file to the remote user.
    - authorized_key: user={{ ansible_user }} key={{ lookup('file', item) }}
      with_fileglob:
        - public_keys/*.pub
