
---
# This playbook configures infrastructure for the Burlington Amateur Radio Club

- hosts: aprx_hosts
  roles:
    - aprx_config

- hosts: power_controllers
  tasks:
    - name: Install the power cyle utility
      pip: name='git+http://github.com/burlington-arc/power-cycle.git#egg=power-cycle'

- include: setup-ssh-users.yml
