
---
# This playbook configures infrastructure for the Burlington Amateur Radio Club

- hosts: aprx_hosts
  roles:
    # This playbook just does the configuration.  Run install-aprx.yml to install it.
    - aprx_config

- hosts: power_controllers
  tasks:
    - name: Install the power cycle utility
      pip:
        name: 'git+http://github.com/burlington-arc/power-cycle.git#egg=power-cycle'
        editable: false


- include: setup-ssh-users.yml
