
---
# This playbook configures infrastructure for the Burlington Amateur Radio Club

- hosts: aprx_hosts
  roles:
    # This playbook just does the configuration.  Run install-aprx.yml to install it.
    - aprx_config

- include: setup-ssh-users.yml
